version: 2

project_name: loop

before:
  hooks:
    - go mod tidy

builds:
  - id: loop
    main: ./cmd/loop
    binary: loop
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.Version={{ .Version }}
      - -X main.GOOS={{ .Os }}
      - -X main.GOARCH={{ .Arch }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    name_template: 'loop_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files: []

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "merge conflict"

release:
  github: 
    owner: sambaths
    name: loop
  draft: false
  replace_existing_draft: true
